<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Title_175_Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Title_175_Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clock\Clock.csproj" />
    <ProjectReference Include="..\Language\Language.csproj" />
    <ProjectReference Include="..\Settings\Settings.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\SettingsWindow\TitleSettingsControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Controls\SettingsWindow\CommonKeysControl.cs" />
    <Compile Update="Controls\SettingsWindow\ActionKeysControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>